version: '3.8'

services:
  db:
    image: leal_db:latest
    container_name: psql_container
    ports:
      - "54321:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leal_container
    environment:
      PORT: 5050
      DATABASE_URL: postgres://postgres:postgres@psql_container:5432/postgres?sslmode=disable
      HASH_COST: 8
    ports:
      - "5050:5050"
    depends_on:
      - db

volumes:
  db_data: